name: DAST - OWASP ZAP Full Scan

on:
  workflow_dispatch:
  pull_request:
    branches: ["main", "master"]

jobs:
  dast:
    runs-on: ubuntu-latest
    services: {}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build package
        run: mvn -B -DskipTests clean package

      - name: Start app in background (port 8080)
        run: |
          nohup java -jar target/*.jar > app.log 2>&1 &
          # wait for app readiness (simple loop; adapt to health endpoint)
          for i in {1..30}; do
            if curl -sSf http://localhost:8080/actuator/health >/dev/null; then
              echo "app ready"; break
            fi
            sleep 2
          done

      - name: Run OWASP ZAP full scan (docker)
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: 'http://localhost:8080'
          cmd_options: '-t 1 -m 10'   # timeout/threads (ajuste)
          fail_threshold: 'HIGH'      # faz o job falhar se encontrar HIGH/VULN
      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            ./zaproxy-report.html
            ./zap-full-scan-report.xml || true
