name: Build & Deploy to Staging

on:
  push:
    branches: ["develop", "staging"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build
        run: mvn -B -DskipTests package

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/myapp:${{ github.sha }} .
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/myapp:${{ github.sha }}

      - name: Trigger deploy (example)
        run: |
          # aqui você pode chamar API do seu CD (Argo, Terraform Cloud, Ansible, etc.)
          echo "chamar deploy em staging via API"
